### PR TITLE
Search for all scene files instead of setting a fixed scene folder

### PR DESCRIPTION
**Pull request by GieziJo**
solves #1, I kept the `scenesFolder` variable as it is used in `ShowBootstrapScene`. Although this function does not seem to be called anywhere, but if needed it's still there.

### CODE REVIEW

**Comment by BennyKok** [comment]
Thanks a lot, for also bumping the version!

Ha, the bootstrap scene's path is basically hardcoded because I mostly have a common scene for holding most of the player's objects, tho not many people might be using the same pattern so it's more of a personal preference. 

I recently decoupled the default toolbar buttons with the new attribute, I might, in future commit, move these specific buttons away from the repo.

**Comment by GieziJo** [comment]
Sure thing :) I wasn't sure how you handle versions, I always struggle with that, if you have any guides I'm quite interested :)

Ok cool!

Yeah that makes sense, I think with how you set things up it could be easy to allow the user to add their custom buttons and just hook up to a delegate or something. I'm open to help if you want :)

In any case great work!

**Comment by BennyKok** [comment]
Oh, I thought you were using standard-version? haha, I usually run through standard-version, and just let it handles the version bump and changelog generation.

you can npx standard-version --dry-run

**Comment by GieziJo** [comment]
cool will check that out, thanks :)

**Comment by BennyKok** [comment]
Oh, btw you can already add custom buttons with the attribute now, e.g.
```
[ToolbarButton(iconName = "Package Manager", tooltip = "Package Manager", order = 0)]
public static void ShowPackageManager()
{
    UnityEditor.PackageManager.UI.Window.Open("");
}
```

sure we can also have delegate, I think that might be similar to how https://github.com/marijnz/unity-toolbar-extender handles it, sadly it's not compatible with the new VisualElement stuff in the editor. 

However, using the attribute + static method way is cleaner (I think) and similar to how unity handles the MenuItem.

Side track,
btw some specific button ideas for me personally, such as opening some software directly, in my case, Fork, haha, I use fork the git client as my daily driver, and having the button there to open fork and point to the right repo will be bravo, good things with the static method will be we can add in the Shortcut attribute easily to assign a shortcut to the same action haha!

**Comment by BennyKok** [comment]
Btw, some little changes i just added incase the scene list grow too long haha
Animation

**Comment by GieziJo** [comment]
> Oh, btw you can already add custom buttons with the attribute now, e.g.
> 
> ```
> [ToolbarButton(iconName = "Package Manager", tooltip = "Package Manager", order = 0)]
> public static void ShowPackageManager()
> {
>     UnityEditor.PackageManager.UI.Window.Open("");
> }
> ```
> 
> sure we can also have delegate, I think that might be similar to how https://github.com/marijnz/unity-toolbar-extender handles it, sadly it's not compatible with the new VisualElement stuff in the editor.
> 
> However, using the attribute + static method way is cleaner (I think) and similar to how unity handles the MenuItem.

Oh yeah I missed that, attributes area amazing! I think it's the right way to go :)


> Side track,
> btw some specific button ideas for me personally, such as opening some software directly, in my case, Fork, haha, I use fork the git client as my daily driver, and having the button there to open fork and point to the right repo will be bravo, good things with the static method will be we can add in the Shortcut attribute easily to assign a shortcut to the same action haha!

Ah cool yeah!

> Btw, some little changes i just added incase the scene list grow too long haha
> Animation

Just saw your change, super cool idea! Also I like th new scene button very much!

**Comment by RunninglVlan** [comment]
> Ha, the bootstrap scene's path is basically hardcoded because I mostly have a common scene for holding most of the player's objects, tho not many people might be using the same pattern so it's more of a personal preference.
> 
> I recently decoupled the default toolbar buttons with the new attribute, I might, in future commit, move these specific buttons away from the repo.
Yeah, about that bootstrap scene, it's pretty specific =D Could you maybe hide it behind `#if TOOLBAR_BUTTON_BOOTSTRAP`?

**Comment by BennyKok** [comment]
Yea, I should probably hide it by default, to be honest, I have not been using it for some time haha!

**Pull request merged**
